# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8caf9051e8dfa801c4847106d0f071e6f56490275a725bc15d6cba9b7e99501600b55614a027d506bad2dd58c40ab65e2d4925e7a4bf99bee45a74fef6353e3

test:
  secret_key_base: a4cc5a7e6f7c7f648325faf05d3e30c23533e8deefc5fe744c438969b4208d9f73b95a9d4b760e145408369f5e75dbe64eccabca065f298a3668700206beb8ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
